# Generated by Django 4.0 on 2022-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_boiler_temp', models.IntegerField(default=50)),
                ('work_feed', models.IntegerField(default=10)),
                ('work_pause', models.IntegerField(default=60)),
                ('work_power', models.IntegerField(default=100)),
                ('is_changed', models.BooleanField(default=False)),
            ],
        ),
    ]
